site:
  title: Antora Docs
  start_page: 7.16.0@docs-es-java::introduction.adoc
content:
  sources:
    - url: .
      branches: [v7.16,v6.8]
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
